#!/bin/bash -eu

index_path=${PEV2_INDEX_PATH:-"$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/pev2-index.html"}
script="
    <script defer>
      const checkForPlanInput = setInterval(() => {
        const planInput = document.getElementById('planInput');
        const queryNameInput = document.getElementById('queryName');
        if (planInput && queryNameInput) {
          clearInterval(checkForPlanInput);
          
          const params = new URLSearchParams(window.location.search);

          const analysis = params.get('analysis');
          if (analysis) {
            planInput.value = analysis;
            planInput.dispatchEvent(new Event('input', { bubbles: true }));
          }

          const name = params.get('name');
          if (name) {
            queryNameInput.value = name;
            queryNameInput.dispatchEvent(new Event('input', { bubbles: true }));
          }
        }
      }, 100);
    </script>
"

wget https://www.github.com/dalibo/pev2/releases/latest/download/index.html -O "$index_path"

printf "%s\n" "$script" | sed -i "/<\/body>/e cat" "$index_path"
